### ISSUE TITLE
Bug: メッセージが複数回表示される, 削除できない

### ISSUE THREAD

**Issue by kazuemon** [yukinashi/youtube-feature-rich-v1#4]
## 概要
「拡張機能がアップデートされました 設定がリセットされた可能性があります」 が複数表示され、非表示にすることができない

## スクリーンショット
![image](https://user-images.githubusercontent.com/12812934/107593725-56d7ca00-6c53-11eb-80bf-fd20c1a1e0e3.png)

## 環境
YouTubeライブを快適に視聴する！！！ (ID: edkjjpjoagffmeekfcjklnhgihjilcfg) v3.1.1
Chrome 88.0.4324.150 / Windows10

**Comment by kazuemon** [comment]
再現手順の記載を忘れておりましたが、自動再生を使用中に発生していると思われます。
なおメッセージが1つのみ表示されている場合は非表示にすることが可能です。

**Comment by fa0311** [comment]
ver3.1.2 で問題を修正しました。
